# Generated by Django 4.1.7 on 2023-02-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_iteraciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Iteraciones',
        ),
    ]
